Repository UKHomeOffice/hocs-toolbox, pull requests merged in 2022-08, with the labels that each got.

#40 HOCS-5050 Add script to simplify case unsticking
  scripts/rectify
Labels: minor

#39 🧱 HOCS-5439: Ubuntu core based images
  Dockerfile
Labels: smoketest, minor

#42 ⬆️ Repoint GH actions to new repo
  .github/workflows/docker-build-branch.yml
  .github/workflows/docker-build-tag.yml
  .github/workflows/pr-check.yml
Labels: skip-release

#41 Remove the greek environment deployments from the .drone.yml
  .drone.yml
Labels: skip-release

#43 Volume mount
  kube/kd/deployment.yaml
Labels: smoketest, minor

#45 HOCS-4830: Revert base image.
  Dockerfile
Labels: smoketest, minor

#46 Revert group user
  Dockerfile
Labels: smoketest, minor

#47 HOCS-5511: Use new faster pipelines
  .dockerignore
  .github/workflows/docker-build-branch.yml
  .github/workflows/docker-build-tag.yml
  .github/workflows/pr-check.yml
Labels: smoketest, patch

#48 Revert to original
  Dockerfile
Labels: minor

#49 HOCS-4830: Remove copy scripts.
  Dockerfile
Labels: minor
